Database:
  Enabled: false
  Url: "localhost"
  Port: 27017
  Username: "user"
  Password: "password"
  Database: "db"
MCL:
  Url: "localhost"
  Port: 8080
  verifyKey: "fill your key here"
Bot:
  BotId: 114514
  Groups:
    - 1919810