Database:
  Enabled: false
  Url: "mongodb://localhost:27017"
MCL:
  Url: "http://127.0.0.1"
  Port: 8080
  verifyKey: "fill your key here"
  queryDelay: 40
  queryPeriod: 40
Bot:
  Debug: false
  BotId: 114514
Message:
  Help: |-
    测试下帮助QWQ
    这个也是QWQ