Database:
  Enabled: false
  Url: "localhost"
  Port: 27017
  Username: "user"
  Password: "password"
  Database: "db"
MCL:
  Url: "http://127.0.0.1"
  Port: 8080
  verifyKey: "fill your key here"
  queryDelay: 2000
Bot:
  Debug: false
  BotId: 114514