Database:
  Enabled: false
  Url: "mongodb://localhost:27017"
  Db: "cave"
MCL:
  Url: "http://127.0.0.1"
  Port: 8080
  verifyKey: "fill your key here"
  queryDelay: 40
  queryPeriod: 40
Bot:
  Debug: false
  BotId: 114514
  BanWord: |-
    傻逼/true/120
  BanPeople: |-
    1919810
  BanLimit: 500
  DetectLimit: 0.75
  CountDown: 10
  SpamMute: 600
Message:
  Help: |-
    测试下帮助QWQ
    这个也是QWQ
  NoPermission: |-
    你没有权限QWQ！
    试试其他的命令吧QWQ
  BotNoPermission: |-
    QAQ，我是个卑微的机器人，不敢禁言这个人呢QAQ
  NoCommand: |-
    啊哦，貌似没找到这个命令呢QWQ？
    也许你可以尝试下.help来查看命令
  NotANumber: |-
    啊哦，貌似输入的不是个数字呢QAQ
  InDeveloping: |-
    貌似这个功能正在开发呢QWQ！
    再等等吧QWQ！
  Recall: |-
    貌似你的发言触发了群主设置的规则QWQ？
    所以被撤回啦QWQ！
  OK: |-
    操作成功完成QWQ！
  Disabled: |-
    功能未开启QAQ...
  BindFailed: |-
    &c貌似绑定失败了QAQ...再检查下你的&6玩家名&c和&6Token&c吧QWQ！
  BindSuccessful: |-
    &a绑定成功QWQ！
  Requested: |-
    申请成功QWQ！
    请在游戏中使用{command}来完成绑定！
  HasBind: |-
    你的QQ已经绑定了{player}！
    不能再绑定了QAQ！
  DontSpam: |-
    不要刷屏哦QWQ!