name: BuildwithMaven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: Upload a Build
        uses: actions/upload-artifact@v2.3.1
        if: success()
        with:
          name: ManageQQ
          path: /home/runner/work/ManageQQ/ManageQQ/target/*.jar
