name: BuildwithMaven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package
      - name: Upload a Build
        uses: actions/upload-artifact@v2.3.1
        with:
          name: "ManageQQ-Bukkit.jar"
          path: /home/runner/work/ManageQQ/ManageQQ/target/ManageQQ-1.0.jar